# Generated by Django 3.1.6 on 2021-05-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PresList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profname',
            new_name='Owner',
        ),
    ]
