# Generated by Django 3.1.6 on 2021-05-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PresList', '0002_auto_20210503_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='namestudent',
            new_name='OwnerID',
        ),
    ]
