# Generated by Django 3.1.6 on 2021-05-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PresList', '0003_auto_20210503_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='empid',
            new_name='bname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sid',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='violation',
            new_name='ir',
        ),
    ]
