# Generated by Django 3.1.6 on 2021-05-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PresList', '0004_auto_20210503_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='OwnerID',
            new_name='fullname',
        ),
    ]
